import React, { useEffect, useRef } from 'react'
import { FaChevronRight } from 'react-icons/fa6'
import { FiArrowUpRight } from 'react-icons/fi'

const NotificationBox = ({ isOpen, onClose }) => {
    const notificationBoxModalRef = useRef(null);
    useEffect(() => {
        const handleClickOutside = (event) => {
            if (notificationBoxModalRef.current && !notificationBoxModalRef.current.contains(event.target)) {
                onClose(); // Call the onClose prop!
            }
        }
        if (isOpen) {
            document.addEventListener('mousedown', handleClickOutside);
        }

        return () => {
            document.removeEventListener('mousedown', handleClickOutside);
        };
    }, [isOpen, onClose]); // Add onClose to the dependency array

    if (!isOpen) return null; // Don't render if not open

    return (
        <>
            <div className="notification-box-wrapper">
                <div className="notification-box-container" ref={notificationBoxModalRef} >
                    <div className="flex items-center justify-between notification-box-header">
                        <h3>Notifications</h3>

                        <a href="" className='mark-notification-as-read-text'>
                            <span>
                                Mark all as read
                            </span>
                        </a>
                    </div>

                    <div className="notification-box-content-area">
                        <div className="notifications-list">
                            {/* can take maximum of 7 Notification items */}
                            <a href="">
                                <div className="notification-item">
                                    <div className="notification-icon" style={{ backgroundColor: "#7D7AE5" }}>
                                        <FiArrowUpRight />
                                    </div>
                                    <div className="notification-content">
                                        <div className="notification-text">Schedule for GNS 301 updated</div>
                                    </div>
                                    <div className="flex items-center notification-time">1hr ago
                                        <FaChevronRight className='notification-text-arrow-icon' />
                                    </div>
                                </div>
                            </a>
                            <a href="">
                                <div className="notification-item">
                                    <div className="notification-icon" style={{ backgroundColor: "#80FFB0" }}>
                                        <FiArrowUpRight />
                                    </div>
                                    <div className="notification-content">
                                        <div className="notification-text">New Request from Dr Adeyemi</div>
                                    </div>
                                    <div className="flex items-center notification-time">1hr ago
                                        <FaChevronRight className='notification-text-arrow-icon' />
                                    </div>
                                </div>
                            </a>

                            <a href="">
                                <div className="notification-item">
                                    <div className="notification-icon" style={{ backgroundColor: "#FF7576" }}>
                                        <FiArrowUpRight />
                                    </div>
                                    <div className="notification-content">
                                        <div className="notification-text">Timetable generated by Registra</div>
                                    </div>
                                    <div className="flex items-center notification-time">1hr ago
                                        <FaChevronRight className='notification-text-arrow-icon' />
                                    </div>
                                </div>
                            </a>

                            <a href="">
                                <div className="notification-item">
                                    <div className="notification-icon" style={{ backgroundColor: "#FF7576" }}>
                                        <FiArrowUpRight />
                                    </div>
                                    <div className="notification-content">
                                        <div className="notification-text">Timetable generated by Registra</div>
                                    </div>
                                    <div className="flex items-center notification-time">1hr ago
                                        <FaChevronRight className='notification-text-arrow-icon' />
                                    </div>
                                </div>
                            </a>

                            <a href="">
                                <div className="notification-item">
                                    <div className="notification-icon" style={{ backgroundColor: "#FF7576" }}>
                                        <FiArrowUpRight />
                                    </div>
                                    <div className="notification-content">
                                        <div className="notification-text">Timetable generated by Registra</div>
                                    </div>
                                    <div className="flex items-center notification-time">1hr ago
                                        <FaChevronRight className='notification-text-arrow-icon' />
                                    </div>
                                </div>
                            </a>
                        </div>
                    </div>
                </div>
            </div>
        </>
    )
}

export default NotificationBox